import type { LevelDef } from '../game/types'

/** Page 1: tides. What floats rises with the water. */
const readingRoom: LevelDef = {
  id: '2-1',
  chapter: 2,
  page: 1,
  title: 'The Reading Room',
  subtitle: 'where the water came in',
  theme: 'library',
  width: 2200,
  spawn: { x: 90, y: 300 },
  exit: { x: 2100, y: 300 },
  terrain: [
    { x: 0, y: 300, w: 500, h: 240 },
    { x: 1700, y: 300, w: 500, h: 240 },
  ],
  pools: [{ x: 500, w: 1200, base: 470, top: 310, bottom: 540 }],
  words: [
    { id: 'silence', text: 'SILENCE', x: 190, y: 225, gold: true },
    {
      id: 'train',
      text: 'TRAIN',
      x: 320,
      y: 300,
      tune: { RAIN: { x: 1100, y: 140, w: 460, h: 100, ly: 170 }, DRAIN: { x: 1100, y: 540 } },
    },
    { id: 'draft', text: 'DRAFT', x: 575, y: 440, tune: { RAFT: { x: 575, dx: 1058, speed: 110 } } },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 2,
  checkpoints: [{ x: 1760, y: 300 }],
  notes: [
    { when: { start: 1 }, text: 'Chapter Two. The library drowned the year I stopped writing.' },
    { when: { start: 5 }, text: 'Your quill holds three letters now.' },
    { when: { x: 130 }, text: 'SILENCE. The Librarian’s rule, written in gold. Gold can’t be changed.' },
    { when: { x: 250 }, text: 'My old toy train. It used to go round and round this room.' },
    { when: { x: 400 }, text: 'A cold draft blows across the water. There’s a raft in it, somewhere.' },
    { when: { word: 'RAFT' }, text: 'A raft! But the far shelf is so high above the water…' },
    { when: { word: 'RAIN' }, text: 'Rain, indoors. The water rises, and everything that floats rises with it.' },
    { when: { word: 'DRAIN' }, text: 'A drain. Everything goes down. Including your raft.' },
    { when: { word: 'RAT' }, text: 'A rat. The library always had rats.' },
  ],
  hints: [
    'The far shelf is high. Something has to lift you.',
    'DRAFT → RAFT. TRAIN → RAIN.',
    'Rain raises the water, and the raft rises with it. Ride it across.',
  ],
  solution: [
    { type: 'pluck', word: 'draft', index: 0 },
    { type: 'pluck', word: 'train', index: 0 },
  ],
}

/** Page 2: lowering the water, and taking a letter from a living thing. */
const stacks: LevelDef = {
  id: '2-2',
  chapter: 2,
  page: 2,
  title: 'The Stacks',
  subtitle: 'shelves that hold up the sky',
  theme: 'library',
  width: 2400,
  spawn: { x: 90, y: 300 },
  exit: { x: 2300, y: 380 },
  terrain: [
    { x: 0, y: 300, w: 520, h: 240 },
    { x: 520, y: 500, w: 1380, h: 40 },
    { x: 1150, y: 0, w: 80, h: 420 },
    { x: 1830, y: 440, w: 70, h: 60 },
    { x: 1900, y: 380, w: 500, h: 160 },
  ],
  pools: [{ x: 520, w: 1380, base: 330, top: 300, bottom: 500 }],
  words: [
    { id: 'ink', text: 'INK', x: 450, y: 300, tune: { SINK: { x: 580, y: 500 } } },
    { id: 'eels', text: 'EELS', x: 720, y: 400, tune: { EELS: { dx: 250, speed: 70 }, EEL: { dx: 640, speed: 95 } } },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 2,
  checkpoints: [
    { x: 560, y: 500 },
    { x: 1950, y: 380 },
  ],
  notes: [
    { when: { start: 1 }, text: 'The Stacks. The shelves go all the way up. The only way through is under.' },
    { when: { x: 300 }, text: 'My inkpot. I left it here the night the water came.' },
    { when: { x: 420 }, text: 'Eels in the ink. A whole school of them. Nasty.' },
    { when: { word: 'EEL' }, text: 'Just the one eel now. Still nasty.' },
    { when: { word: 'SINK' }, text: 'A sink! Pull the plug, and down it all goes.' },
    { when: { x: 700 }, text: 'Mind the eel. They flop about, out of the water.' },
    { when: { word: 'INKS' }, text: 'More ink. Exactly what this place needed.' },
  ],
  hints: [
    'The water has to go somewhere. What swallows water?',
    'EELS has a spare letter. INK needs one.',
    'EELS → EEL, then S + INK → SINK. Jump the eel.',
  ],
  solution: [
    { type: 'pluck', word: 'eels', index: 3 },
    { type: 'place', word: 'ink', index: 0, letter: 'S' },
  ],
}

/** Page 3: darkness, lost letters, and a letter swap. */
const archive: LevelDef = {
  id: '2-3',
  chapter: 2,
  page: 3,
  title: 'The Archive of Lost Words',
  subtitle: 'where cut words go',
  theme: 'archive',
  width: 2600,
  dark: true,
  spawn: { x: 90, y: 460 },
  exit: { x: 2500, y: 200 },
  terrain: [
    { x: 0, y: 460, w: 900, h: 80 },
    { x: 520, y: 400, w: 80, h: 60 },
    { x: 900, y: 200, w: 600, h: 340 },
    { x: 1900, y: 200, w: 700, h: 340 },
  ],
  pools: [{ x: 1500, w: 400, base: 420, top: 420, bottom: 540 }],
  letters: [{ id: 'p', letter: 'P', x: 560, y: 300 }],
  words: [
    { id: 'cage', text: 'CAGE', x: 850, y: 460, tune: { CAGE: { ly: 420 }, PAGE: { y: 468, dy: -254, speed: 70 } } },
    { id: 'candle', text: 'CANDLE', x: 1470, y: 200, gold: true },
    { id: 'row', text: 'ROW', x: 1700, y: 150, tune: { CROW: { x: 1560, y: 232, dx: 280, speed: 90 } } },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 3,
  checkpoints: [
    { x: 960, y: 200 },
    { x: 1960, y: 200 },
  ],
  diary: { id: 'diary-2', x: 1200, y: 125, onlyInDark: true },
  notes: [
    { when: { start: 1 }, text: 'The Archive. Where I kept the words I cut. They never forgave me.' },
    { when: { start: 5 }, text: 'Lost letters glow in the dark. Catch one, and it’s yours.' },
    { when: { event: 'letter' }, text: 'A lost letter. Look after it.' },
    { when: { x: 640 }, text: 'A cage at the foot of the shelves. Something used to go up and down here.' },
    { when: { word: 'AGE' }, text: 'Age. It gets into everything down here.' },
    { when: { word: 'PAGE' }, text: 'A page! Pages turn. This one lifts.' },
    { when: { x: 1320 }, text: 'That candle is gold. It’s the Librarian’s. But its light is free.' },
    { when: { word: 'CROW' }, text: 'A crow. It carries things across. Mostly secrets.' },
    { when: { event: 'diary' }, text: 'That one. I wrote it the day after.' },
  ],
  hints: [
    'Letters that glow in the dark can be caught. Jump for it.',
    'Take the C out of CAGE, and put the P in its place.',
    'A ROW with a C in front of it can fly.',
  ],
  solution: [
    { type: 'pluck', word: 'cage', index: 0 },
    { type: 'place', word: 'cage', index: 0, letter: 'P' },
    { type: 'place', word: 'row', index: 0, letter: 'C' },
  ],
}

/** Page 4: the Librarian. It can't be changed, only distracted. */
const librarian: LevelDef = {
  id: '2-4',
  chapter: 2,
  page: 4,
  title: 'The Librarian',
  subtitle: 'keeper of thrown-away words',
  theme: 'library',
  width: 2600,
  restartOnDeath: true,
  spawn: { x: 90, y: 460 },
  exit: { x: 2480, y: 460 },
  terrain: [
    { x: 0, y: 460, w: 2600, h: 80 },
    { x: 300, y: 320, w: 460, h: 20 },
  ],
  letters: [{ id: 's', letter: 'S', x: 150, y: 430 }],
  words: [
    { id: 'book', text: 'BOOK', x: 262, y: 460 },
    { id: 'bring', text: 'BRING', x: 640, y: 400, tune: { RING: { x: 640, y: 460 } } },
    { id: 'librarian', text: 'LIBRARIAN', x: 2200, y: 460, gold: true },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 2,
  notes: [
    { when: { start: 1 }, text: 'Shh. This is the Librarian’s hall.' },
    { when: { x: 200 }, text: 'That shelf is too high to jump. Books make good steps.' },
    { when: { word: 'BOOKS' }, text: 'A stack of books. Better for standing on than reading, apparently.' },
    { when: { x: 460 }, text: 'The Librarian keeps every word I ever threw away. It can’t be changed. It can only be distracted.' },
    { when: { x: 560 }, text: '“Please BRING your books back.” It hates noise more than lost books.' },
    { when: { word: 'RING' }, text: 'A bell! Now hide. Up on the shelf. Hide!' },
    { when: { event: 'shush' }, text: '“SHHHHHHH.”' },
    { when: { word: 'HUSH' }, text: 'It silenced the bell. Go, while its back is turned.' },
    { when: { x: 1500 }, text: 'Don’t look back. It doesn’t like being looked at.' },
  ],
  hints: [
    'Catch the S. BOOK + S → BOOKS, a step up to the shelf.',
    'The Librarian goes wherever there is noise.',
    'From the shelf: BRING → RING. Wait for it to pass beneath you, then run.',
  ],
  solution: [
    { type: 'place', word: 'book', index: 4, letter: 'S' },
    { type: 'pluck', word: 'bring', index: 0 },
  ],
}

/** Page 5: the flood. Climb, and let the water come to you. */
const flood: LevelDef = {
  id: '2-5',
  chapter: 2,
  page: 5,
  title: 'The Flood',
  subtitle: 'the tower of the Drowned Library',
  theme: 'flood',
  width: 1100,
  height: 1500,
  restartOnDeath: true,
  spawn: { x: 120, y: 1440 },
  exit: { x: 1000, y: 640 },
  terrain: [
    { x: 0, y: 1440, w: 1100, h: 60 },
    { x: 316, y: 1200, w: 384, h: 24 },
    { x: 1000, y: 1200, w: 100, h: 24 },
    { x: 850, y: 1110, w: 100, h: 20 },
    { x: 1000, y: 1020, w: 100, h: 20 },
    { x: 400, y: 940, w: 560, h: 24 },
    { x: 0, y: 700, w: 440, h: 24 },
    { x: 800, y: 640, w: 300, h: 24 },
  ],
  pools: [{ x: 0, w: 1100, base: 1700, top: 560, bottom: 1500, rise: { speed: 24, delay: 4 } }],
  letters: [{ id: 'l', letter: 'L', x: 900, y: 880 }],
  words: [
    { id: 'trope', text: 'TROPE', x: 300, y: 1330, tune: { ROPE: { x: 300, y: 1440, h: 262 } } },
    {
      id: 'rain',
      text: 'RAIN',
      x: 560,
      y: 1030,
      tune: { RAIN: { y: 1070, w: 360, h: 90, ly: 1150 }, TRAIN: { x: 750, y: 1226, dx: 200, speed: 90 } },
    },
    { id: 'adder', text: 'ADDER', x: 470, y: 940, tune: { LADDER: { x: 460, y: 940, h: 262 } } },
    { id: 'flood', text: 'FLOOD', x: 150, y: 1500, tune: { FLOOR: { x: 550, w: 1100, lx: 150 } } },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 6,
  notes: [
    { when: { start: 0.8 }, text: 'The water’s coming in. The whole library is going under. Climb!' },
    { when: { start: 3.5 }, text: 'A trope, hanging there. Overused. But there’s a rope in every trope.' },
    { when: { word: 'ROPE' }, text: 'Climb! Hold ↑.' },
    { when: { y: 1210 }, text: 'That rain is filling the tower faster. It’s missing a letter. The one you’re holding?' },
    { when: { word: 'TRAIN' }, text: 'The toy train! It still runs. Jump on.' },
    { when: { y: 1120 }, text: 'Take what you need from what you leave behind. You won’t be coming back down.' },
    { when: { y: 950 }, text: 'An adder, blocking the way up. We’ve met. And something glows over there…' },
    { when: { word: 'LADDER' }, text: 'Old tricks still work.' },
    { when: { y: 710 }, text: 'The way out is too far. Let the water come up to meet you. Then change it.' },
    { when: { word: 'FLOO' }, text: 'It stopped. It’s holding its breath. Now finish the word.' },
    { when: { word: 'FLOOR' }, text: 'A floor. The flood is only a floor now. Walk on it.' },
  ],
  hints: [
    'Every trope hides a rope.',
    'T + RAIN → TRAIN. Pluck an R from something you’ve finished with.',
    'Wait for the FLOOD to rise close, then FLOOD → FLOO → FLOOR.',
  ],
  solution: [
    { type: 'pluck', word: 'trope', index: 0 },
    { type: 'place', word: 'rain', index: 0, letter: 'T' },
    { type: 'pluck', word: 'trope', index: 0 },
    { type: 'place', word: 'adder', index: 0, letter: 'L' },
    { type: 'pluck', word: 'flood', index: 4 },
    { type: 'place', word: 'flood', index: 4, letter: 'R' },
  ],
}

export const CHAPTER_2: LevelDef[] = [readingRoom, stacks, archive, librarian, flood]
