import type { LevelDef } from '../game/types'

/** Page 1: Then & Now. A bridge that was, a seed that grows. */
const stoppedClock: LevelDef = {
  id: '3-1',
  chapter: 3,
  page: 1,
  title: 'The Stopped Clock',
  subtitle: 'where every clock stopped at once',
  theme: 'clock',
  width: 2000,
  eras: { start: 'present' },
  spawn: { x: 90, y: 460 },
  exit: { x: 1900, y: 300 },
  terrain: [
    { x: 0, y: 460, w: 900, h: 80 },
    { x: 880, y: 460, w: 290, h: 14, era: 'past' },
    { x: 1150, y: 460, w: 400, h: 80 },
    { x: 1550, y: 300, w: 450, h: 240 },
  ],
  words: [{ id: 'speed', text: 'SPEED', x: 1470, y: 440, era: 'past', tune: { SEED: { y: 460 }, TREE: { x: 1515, y: 460 } } }],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 1,
  checkpoints: [{ x: 1200, y: 460 }],
  notes: [
    { when: { start: 1 }, text: 'The Clockwork Tower. Every clock in it stopped at the same minute.' },
    { when: { start: 5 }, text: 'But I can still turn the hands. Press F to go back to Then. F again for Now.' },
    { when: { x: 660 }, text: 'The bridge is gone. It was here, once. Go back to when it was.' },
    { when: { event: 'past' }, text: 'Then. Everything is younger here. So was I.' },
    { when: { x: 1280 }, text: 'Speed. Everything rushed, back then. Slow it down.' },
    { when: { word: 'SEED' }, text: 'A seed. Plant something Then, and by Now it has grown.' },
    { when: { event: 'present' }, text: 'Now. Whatever you changed Then is still changed.' },
  ],
  hints: [
    'The bridge only exists Then. Press F (or the ⟲ button).',
    'Words that live Then can only be changed Then.',
    'SPEED → SEED in the past. By Now it is a TREE.',
  ],
  solution: [{ type: 'pluck', word: 'speed', index: 1 }],
}

/** Page 2: iron rusts, cubs grow up, stone just waits. */
const ironRust: LevelDef = {
  id: '3-2',
  chapter: 3,
  page: 2,
  title: 'Iron & Rust',
  subtitle: 'the lower gears',
  theme: 'clock',
  width: 2600,
  eras: { start: 'present' },
  spawn: { x: 90, y: 460 },
  exit: { x: 2500, y: 460 },
  terrain: [
    { x: 0, y: 460, w: 700, h: 80 },
    { x: 700, y: 330, w: 700, h: 210 },
    { x: 1400, y: 460, w: 400, h: 80 },
    { x: 1790, y: 460, w: 320, h: 14, era: 'past' },
    { x: 2100, y: 460, w: 500, h: 80 },
  ],
  letters: [{ id: 'e', letter: 'E', x: 320, y: 420, era: 'past' }],
  words: [
    { id: 'cub', text: 'CUB', x: 640, y: 460, era: 'past', tune: { CUBE: { x: 630 } } },
    { id: 'iron', text: 'IRON', x: 1600, y: 460, era: 'past' },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 1,
  checkpoints: [
    { x: 760, y: 330 },
    { x: 1450, y: 460 },
    { x: 2150, y: 460 },
  ],
  notes: [
    { when: { start: 1 }, text: 'A bear, at the foot of the step. It was only a cub, once.' },
    { when: { event: 'past' }, text: 'Look at it. Tiny. That’s what it grows up into.' },
    { when: { event: 'letter' }, text: 'An E, lost in the past. Somebody dropped it long ago.' },
    { when: { word: 'CUBE' }, text: 'A cube. Stone doesn’t grow up. It just waits for you.' },
    { when: { x: 1440 }, text: 'An iron gate. Iron rusts, if you give it long enough.' },
    { when: { x: 1700 }, text: 'No bridge Now. There was one Then.' },
  ],
  hints: [
    'Change the bear while it is still a cub.',
    'Catch the E in the past. CUB + E → CUBE.',
    'Pass the gate Now. Cross the bridge Then.',
  ],
  solution: [{ type: 'place', word: 'cub', index: 3, letter: 'E' }],
}

/** Page 3: plant an oak, put out a fire before it started. */
const orchard: LevelDef = {
  id: '3-3',
  chapter: 3,
  page: 3,
  title: 'The Orchard of Hours',
  subtitle: 'a garden inside the tower',
  theme: 'clock',
  width: 2200,
  eras: { start: 'present' },
  spawn: { x: 90, y: 460 },
  exit: { x: 2100, y: 160 },
  terrain: [
    { x: 0, y: 460, w: 1600, h: 80 },
    { x: 1080, y: 240, w: 60, h: 220, era: 'past' },
    { x: 1600, y: 160, w: 600, h: 380 },
  ],
  words: [
    { id: 'wheat', text: 'WHEAT', x: 480, y: 460, era: 'past' },
    { id: 'spark', text: 'SPARK', x: 1110, y: 460, era: 'past', tune: { FIRE: { w: 160, h: 110 } } },
    { id: 'corn', text: 'CORN', x: 1540, y: 460, era: 'past', tune: { OAK: { x: 1540 } } },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 3,
  checkpoints: [{ x: 1250, y: 460 }],
  diary: { id: 'diary-3', x: 640, y: 360, era: 'past' },
  notes: [
    { when: { start: 1 }, text: 'The Orchard of Hours. We planted it together, the summer before.' },
    { when: { x: 820 }, text: 'A fire, Now. Then, there was a wall. You can’t get past either.' },
    { when: { word: 'PARK' }, text: 'No spark, no fire. It never happened.' },
    { when: { word: 'SPAR' }, text: 'A spar of wood. It never caught.' },
    { when: { x: 1380 }, text: 'That balcony is so high. Only something very old could reach it.' },
    { when: { word: 'ACORN' }, text: 'An acorn. Oaks take a long time. Luckily, you have one.' },
    { when: { event: 'diary' }, text: 'I hid that page in the past. Of course you found it.' },
  ],
  hints: [
    'A fire Now started as a spark Then.',
    'WHEAT has an A to spare. CORN needs one.',
    'SPARK → PARK. WHEAT → WHET. A + CORN → ACORN, and by Now it is an OAK.',
  ],
  solution: [
    { type: 'pluck', word: 'wheat', index: 3 },
    { type: 'pluck', word: 'spark', index: 0 },
    { type: 'place', word: 'corn', index: 0, letter: 'A' },
  ],
}

/** Page 4: gears turn only Then; a drip becomes a pond. */
const gears: LevelDef = {
  id: '3-4',
  chapter: 3,
  page: 4,
  title: 'The Gears',
  subtitle: 'where the tower keeps its time',
  theme: 'clock',
  width: 2600,
  eras: { start: 'present' },
  spawn: { x: 90, y: 460 },
  exit: { x: 2500, y: 460 },
  terrain: [
    { x: 0, y: 460, w: 600, h: 80 },
    { x: 1400, y: 460, w: 200, h: 80 },
    { x: 1600, y: 460, w: 300, h: 80, era: 'present' },
    { x: 1900, y: 460, w: 700, h: 80 },
  ],
  words: [
    { id: 'g1', text: 'GEAR', x: 690, y: 460, era: 'past' },
    { id: 'g2', text: 'GEAR', x: 870, y: 340, era: 'past', tune: { GEAR: { dy: 120, speed: 60 } } },
    { id: 'g3', text: 'GEAR', x: 1050, y: 460, era: 'past' },
    { id: 'g4', text: 'GEAR', x: 1230, y: 340, era: 'past', tune: { GEAR: { dy: 120, speed: 60 } } },
    { id: 'drip', text: 'DRIP', x: 1750, y: 360, era: 'past', tune: { POND: { x: 1750, y: 460 } } },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 1,
  checkpoints: [{ x: 1450, y: 460 }],
  notes: [
    { when: { start: 1 }, text: 'The gears stopped when the clock stopped. Now they’re just cogs, stuck where they fell.' },
    { when: { x: 420 }, text: 'Then, they turned.' },
    { when: { x: 1480 }, text: 'A pond, Now. And Then, no floor at all.' },
    { when: { word: 'RIP' }, text: 'Rip. That’s what I did to this page, once.' },
    { when: { word: 'DIP' }, text: 'Just a dip. The pond never filled.' },
  ],
  hints: [
    'The cogs Now are stuck. Then, the gears move. Time your jumps.',
    'Where does a pond come from?',
    'DRIP → RIP in the past, then walk across Now.',
  ],
  solution: [{ type: 'pluck', word: 'drip', index: 0 }],
}

/** Page 5: midnight. The clock turns time on its own. */
const midnight: LevelDef = {
  id: '3-5',
  chapter: 3,
  page: 5,
  title: 'Midnight',
  subtitle: 'the top of the tower',
  theme: 'clock',
  width: 1100,
  height: 1300,
  eras: { start: 'present', manual: false, auto: { period: 4.5, warn: 1.2 } },
  spawn: { x: 40, y: 1240 },
  exit: { x: 800, y: 60 },
  terrain: [
    { x: 0, y: 1240, w: 1100, h: 60 },
    { x: 120, y: 1140, w: 160, h: 20 },
    { x: 360, y: 1060, w: 120, h: 20, era: 'present' },
    { x: 560, y: 980, w: 140, h: 20 },
    { x: 780, y: 900, w: 120, h: 20, era: 'past' },
    { x: 980, y: 820, w: 120, h: 24 },
    { x: 420, y: 740, w: 480, h: 24 },
    { x: 0, y: 380, w: 480, h: 24 },
    { x: 560, y: 300, w: 120, h: 20, era: 'present' },
    { x: 760, y: 220, w: 120, h: 20 },
    { x: 960, y: 140, w: 120, h: 20, era: 'past' },
    { x: 740, y: 60, w: 160, h: 24 },
  ],
  letters: [{ id: 'n', letter: 'N', x: 1040, y: 770, era: 'present' }],
  words: [
    { id: 'beat', text: 'BEAT', x: 560, y: 730, era: 'past', tune: { BEAN: { x: 520, y: 740 }, STALK: { x: 520, y: 740 } } },
    { id: 'clock', text: 'CLOCK', x: 820, y: 740 },
  ],
  powers: ['pluck', 'place'],
  quill: 3,
  par: 2,
  notes: [
    { when: { start: 0.8 }, text: 'Midnight. The clock turns time by itself up here. Listen for the ticking.' },
    { when: { start: 5 }, text: 'Some steps only exist Then, some only Now. Wait for yours.' },
    { when: { event: 'strike' }, text: 'Every strike, the tower changes its mind.' },
    { when: { y: 830 }, text: 'A beat, Then. A heartbeat. It could be a bean, with the right letter.' },
    { when: { word: 'BEAN' }, text: 'A bean. By Now, a beanstalk. Climb it while it’s Now.' },
    { when: { word: 'LOCK' }, text: 'You locked time. Careful which moment you keep.' },
    { when: { y: 390 }, text: 'Nearly there. Keep to the rhythm.' },
  ],
  hints: [
    'Wait on the steps that exist in both times. Move when the ticking warns you.',
    'Catch the N (Now). Then, BEAT → BEA → BEAN.',
    'Climb the STALK right after the clock strikes Now.',
  ],
  solution: [
    { type: 'pluck', word: 'beat', index: 3 },
    { type: 'place', word: 'beat', index: 3, letter: 'N' },
  ],
}

export const CHAPTER_3: LevelDef[] = [stoppedClock, ironRust, orchard, gears, midnight]
